#!/bin/sh

name=$1

if ! test -f run; then
  cd config
fi

cc -o $name $name.c

if ./$name; then
  rm $name
  echo "[CONFIG] $1: yes"
  exit 0
else
  rm $name
  echo "[CONFIG] $1: no"
  exit 1
fi

exit $code
