#!/bin/sh

name=$1

if ! test -f run; then
  cd config
fi

if test -z $CC; then
  $CC='cc'
fi

$CC $CFLAGS -o $name $name.c
if test $? != 0; then
  echo "[CONFIG] $1: error"
  exit 2
fi

if ./$name; then
  rm $name
  echo "[CONFIG] $1: yes"
  exit 0
else
  rm $name
  echo "[CONFIG] $1: no"
  exit 1
fi
