#cmakedefine HAVE_ALLOCA_H 1
#cmakedefine HAVE_PROTOTYPES 1
#cmakedefine HAVE_STDARG_PROTOTYPES 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_SYS_TIMES_H 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_UNISTD_H 1

#define SIZEOF_INT @SIZEOF_INT@
#define SIZEOF_LONG @SIZEOF_LONG@
#define SIZEOF_SHORT @SIZEOF_SHORT@

#cmakedefine USE_COMBINATION_EXPLOSION_CHECK 1
#cmakedefine USE_CRNL_AS_LINE_TERMINATOR 1
