class Compiler
  module Bootstrap
    HINTS = {
      :Array=>{:@total=>0, :@tuple=>1, :@start => 2, :@shared => 3},
      :BlockContext=>{},
      :BlockEnvironment=>{:@__ivars__=>0, :@home=>1, :@initial_ip=>2, :@last_ip=>3, :@post_send=>4, :@home_block => 5, :@local_count => 6, :@metadata_container => 7, :@method => 8},
      :Class=>{:@__ivars__=>0, :@method_table=>1, :@method_cache=>2, :@name=>3, :@constants=>4, :@encloser=>5, :@superclass=>6, :@instance_fields=>7, :@has_ivars=>8, :@needs_cleanup=>9, :@object_type=>10},
      :CompiledMethod=>{:@__ivars__=>0, :@primitive => 1, :@required=>2, :@serial=>3, :@bytecodes=>4, :@name=>5, :@file=>6, :@local_count=>7, :@literals=>8, :@total_args => 9, :@splat => 10, :@exceptions=>11, :@lines=>12, :@path=>13, :@bonus => 15, :@compiled => 16, :@staticscope => 17, :@args => 18},
      :Exception => {:@__ivars__ => 0, :@message => 1, :@context => 2 },
      :Float=>{},
      :Hash=>{:@__ivars__=>0, :@keys=>1, :@values=>2,:@bins=>3, :@entries=>4, :@default=>5, :@default_proc=>6},
      :IO=>{:@__ivars__ => 0, :@descriptor => 1, :@buffer => 2, :@mode => 3 },
      :LookupTable => {:@values=>1, :@bins=>2, :@entries=>3},
      :MatchData=>{:@__ivars__=>0, :@source=>1, :@regexp=>2, :@full=>3, :@region=>4},
      :MetaClass=>{:@__ivars__=>0, :@method_table=>1, :@method_cache=>2, :@name=>3, :@constants=>4, :@encloser=>5, :@superclass=>6, :@instance_fields=>7, :@has_ivars=>8, :@needs_cleanup=>9, :@object_type=>10, :@attached_instance=>11},
      :MethodContext=>{},
      :MethodTable=>{:@values=>1, :@bins=>2, :@entries=>3},
      :Module=>{:@__ivars__=>0, :@method_table=>1, :@method_cache=>2, :@name=>3, :@constants=>4, :@encloser=>5, :@superclass => 6},
      :Object=>{:@__ivars__=>0},
      :Regexp=>{:@__ivars__=>0, :@source=>1, :@data => 2, :@names=>3},
      :Selector => {:@name => 0, :@send_sites => 1 },
      :StaticScope => {:@__ivars__ => 0, :@module => 1, :@parent => 2 },
      :String=>{:@bytes=>0, :@characters=>1, :@encoding=>2, :@data=>3, :@hash => 4, :@shared => 5},
      :SymbolTable=>{:@__ivars__=>0,:@symbols=>1, :@strings=>2},
    }

    TYPES = {
      :array => :Array,
      :bignum => :Bignum,
      :blokctx => :BlockContext,
      :blokenv => :BlockEnvironment,
      :bytearray => :ByteArray,
      :class => :Class,
      :cmethod => :CompiledMethod,
      :exception => :Exception,
      :floatpoint => :Float,
      :hash => :Hash,
      :io => :IO,
      :lookuptable => :LookupTable,
      :matchdata => :MatchData,
      :metaclass => :MetaClass,
      :methctx => :MethodContext,
      :methtbl => :MethodTable,
      :module => :Module,
      :object => :Object,
      :regexp => :Regexp,
      :regexpdata => :RegexpData,
      :selector => :Selector,
      :staticscope => :StaticScope,
      :string => :String,
      :symbol => :Symbol,
      :symtbl => :SymbolTable,
      :tuple => :Tuple,
    }
  end
end
