# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/test/unit.rb'

Hoe.new('miniunit', Test::Unit::VERSION) do |p|
  p.rubyforge_name = 'bfts'
  p.description = p.paragraphs_of('README.txt', 2).join("\n\n")
  p.summary = p.description.split(/\. /)[0] + "."
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
end

# vim: syntax=Ruby
