require 'rake'
require 'rake/testtask'

task :default => [:clean, 'subtend_test.bundle']


task :clean do
  rm_rf 'subtend_test.bundle'
end

file 'subtend_test.bundle' do
  sh "cc -dynamic -bundle -undefined suppress -flat_namespace -I ../../shotgun/lib/subtend -g -o subtend_test.bundle subtend_test.c"
end 