def test_case
{"RawParseTree"=>
  [:block,
   [:lasgn, :var1, [:lit, 1]],
   [:lasgn, :var2, [:lit, 2]],
   [:lasgn, :result, [:nil]],
   [:case,
    [:lvar, :var1],
    [:when,
     [:array, [:lit, 1]],
     [:case,
      [:lvar, :var2],
      [:when, [:array, [:lit, 1]], [:lasgn, :result, [:lit, 1]]],
      [:when, [:array, [:lit, 2]], [:lasgn, :result, [:lit, 2]]],
      [:lasgn, :result, [:lit, 3]]]],
    [:when,
     [:array, [:lit, 2]],
     [:case,
      [:lvar, :var2],
      [:when, [:array, [:lit, 1]], [:lasgn, :result, [:lit, 4]]],
      [:when, [:array, [:lit, 2]], [:lasgn, :result, [:lit, 5]]],
      [:lasgn, :result, [:lit, 6]]]],
    [:lasgn, :result, [:lit, 7]]]],
 "Ruby"=>
  "var1 = 1\nvar2 = 2\nresult = nil\ncase var1\nwhen 1 then\n  case var2\n  when 1 then\n    result = 1\n  when 2 then\n    result = 2\n  else\n    result = 3\n  end\nwhen 2 then\n  case var2\n  when 1 then\n    result = 4\n  when 2 then\n    result = 5\n  else\n    result = 6\n  end\nelse\n  result = 7\nend\n",
 "ParseTree"=>
  s(:block,
   s(:lasgn, :var1, s(:lit, 1)),
   s(:lasgn, :var2, s(:lit, 2)),
   s(:lasgn, :result, s(:nil)),
   s(:case,
    s(:lvar, :var1),
    s(:when,
     s(:array, s(:lit, 1)),
     s(:case,
      s(:lvar, :var2),
      s(:when, s(:array, s(:lit, 1)), s(:lasgn, :result, s(:lit, 1))),
      s(:when, s(:array, s(:lit, 2)), s(:lasgn, :result, s(:lit, 2))),
      s(:lasgn, :result, s(:lit, 3)))),
    s(:when,
     s(:array, s(:lit, 2)),
     s(:case,
      s(:lvar, :var2),
      s(:when, s(:array, s(:lit, 1)), s(:lasgn, :result, s(:lit, 4))),
      s(:when, s(:array, s(:lit, 2)), s(:lasgn, :result, s(:lit, 5))),
      s(:lasgn, :result, s(:lit, 6)))),
    s(:lasgn, :result, s(:lit, 7))))}
end
