def test_case
{"RawParseTree"=>
  [:iter,
   [:fcall, :a],
   nil,
   [:block,
    [:dasgn_curr, :v, [:nil]],
    [:iter,
     [:fcall, :assert_block, [:array, [:vcall, :full_message]]],
     nil,
     [:begin,
      [:rescue,
       [:yield],
       [:resbody,
        [:array, [:const, :Exception]],
        [:block, [:dasgn, :v, [:gvar, :$!]], [:break]]]]]]]],
 "Ruby"=>
  "a do\n  v = nil\n  assert_block(full_message) do\n    begin\n      yield\n    rescue Exception => v\n      break\n    end\n  end\nend",
 "ParseTree"=>
  s(:iter,
   s(:call, nil, :a, s(:arglist)),
   nil,
   s(:block,
    s(:lasgn, :v, s(:nil)),
    s(:iter,
     s(:call,
      nil,
      :assert_block,
      s(:arglist, s(:call, nil, :full_message, s(:arglist)))),
     nil,
     s(:rescue,
      s(:yield),
      s(:resbody,
       s(:array, s(:const, :Exception), s(:lasgn, :v, s(:gvar, :$!))),
       s(:break))))))}
end
