def test_case
{"RawParseTree"=>
  [:defn,
   :f,
   [:scope,
    [:block,
     [:args,
      :a,
      :b,
      :c,
      [:block,
       [:lasgn, :a, [:lit, 42]],
       [:lasgn, :b, [:str, "1"]],
       [:lasgn,
        :c,
        [:iter, [:fcall, :lambda], [:dasgn_curr, :n], [:dvar, :n]]]]],
     [:nil]]]],
 "Ruby"=>"def f(a = 42, b = '1', c=lambda {|n| n })\n  # do nothing\nend",
 "RubyParser"=>
  s(:defn,
   :f,
   s(:args,
    :a,
    :b,
    :c,
    s(:block,
     s(:lasgn, :a, s(:lit, 42)),
     s(:lasgn, :b, s(:str, "1")),
     s(:lasgn,
      :c,
      s(:iter,
       s(:call, nil, :lambda, s(:arglist)),
       s(:lasgn, :n),
       s(:lvar, :n))))),
   s(:scope, s(:block, s(:nil))))}
end
