def test_case
{"RawParseTree"=>
  [:block,
   [:lasgn, :b, [:lit, 42]],
   [:defn,
    :a,
    [:scope,
     [:block,
      [:args],
      [:iter,
       [:fcall, :c],
       nil,
       [:begin,
        [:rescue,
         [:vcall, :do_stuff],
         [:resbody,
          [:array, [:const, :RuntimeError]],
          [:block,
           [:dasgn_curr, :b, [:gvar, :$!]],
           [:fcall, :puts, [:array, [:dvar, :b]]]]]]]]]]]],
 "Ruby"=>
  "b = 42\ndef a\n  c do\n    begin\n      do_stuff\n    rescue RuntimeError => b\n      puts(b)\n    end\n  end\nend\n",
 "ParseTree"=>
  s(:block,
   s(:lasgn, :b, s(:lit, 42)),
   s(:defn,
    :a,
    s(:args),
    s(:scope,
     s(:block,
      s(:iter,
       s(:call, nil, :c, s(:arglist)),
       nil,
       s(:rescue,
        s(:call, nil, :do_stuff, s(:arglist)),
        s(:resbody,
         s(:array, s(:const, :RuntimeError), s(:lasgn, :b, s(:gvar, :$!))),
         s(:call, nil, :puts, s(:arglist, s(:lvar, :b))))))))))}
end
