module FileTest
  module_function :blockdev?,
                  :chardev?,
                  :directory?,
                  :executable?,
                  :executable_real?,
                  :exist?,
                  :exists?,
                  :file?,
                  :grpowned?,
                  :identical?,
                  :owned?,
                  :pipe?,
                  :readable?,
                  :readable_real?,
                  :setgid?,
                  :setuid?,
                  :size,
                  :size?,
                  :socket?,
                  :sticky?,
                  :symlink?,
                  :writable?,
                  :writable_real?,
                  :zero?
end
