#ifndef RBX_CAPI_VERSION_H
#define RBX_CAPI_VERSION_H

#define RUBY_VERSION_MAJOR 1
#define RUBY_VERSION_MINOR 8
#define RUBY_VERSION_TEENY 7
#define RUBY_RELEASE_YEAR 2010
#define RUBY_RELEASE_MONTH 6
#define RUBY_RELEASE_DAY 3

#endif
