# Setup project files
project_files = common_headers + headers + sources + objects

add_rbx_capi

add_shared_lib "crypto"

digest = "digest.#{$DLEXT}"

file digest => project_files

desc "Build Digest extension"
task :build => digest
