require 'rake/loaders/makefile'

# Setup project files
project_files = common_headers + headers + sources + objects

add_rbx_capi

add_shared_lib "crypto"

digest = "digest.#{$DLEXT}"

file digest => project_files

graph_dependencies sources

import dependency_file

desc "Build Digest extension"
task :build => digest
