
/* This file was generated by Ragel. Your edits will be lost.
 *
 * This is a state machine implementation of String#unpack.
 *
 * vim: filetype=cpp
 */

#include "vm.hpp"
#include "object_utils.hpp"

#include "builtin/array.hpp"
#include "builtin/exception.hpp"
#include "builtin/string.hpp"

namespace rubinius {

#define UNPACK_ELEMENTS(format)                   \
  for(; index < stop; count--, index += width) {  \
    array->append(state, format(bytes + index));  \
  }

#define BYTE(p)  (Fixnum::from(*((signed char*)p)))

#define UBYTE(p) (Fixnum::from(*((unsigned char*)p)))

  Array* String::unpack(STATE, String* directives) {
    // Ragel-specific variables
    const char *p  = directives->c_str();
    const char *pe = p + directives->size();
    const char *eof = pe;
    int cs;

    // pack-specific variables
    uint8_t* bytes = byte_address();
    size_t index = 0;
    size_t stop = 0;
    size_t width = 0;
    int count = 0;
    bool rest = false;
    Array* array = Array::create(state, 0);


static const int unpack_start = 1;
static const int unpack_first_final = 2;
static const int unpack_error = 0;

static const int unpack_en_main = 1;


	{
	cs = unpack_start;
	}

	{
	if ( p == pe )
		goto _test_eof;
	switch ( cs )
	{
case 1:
	switch( (*p) ) {
		case 67: goto tr0;
		case 99: goto tr2;
	}
	goto st0;
st0:
cs = 0;
	goto _out;
tr0:
	{
    count = 1;
    rest = false;
  }
	goto st2;
tr7:
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st2;
tr14:
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st2;
tr17:
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st2;
tr21:
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st2;
st2:
	if ( ++p == pe )
		goto _test_eof2;
case 2:
	switch( (*p) ) {
		case 0: goto tr3;
		case 32: goto tr3;
		case 33: goto tr4;
		case 42: goto st9;
		case 67: goto tr7;
		case 95: goto tr4;
		case 99: goto tr8;
	}
	if ( (*p) > 13 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr6;
	} else if ( (*p) >= 9 )
		goto tr3;
	goto st0;
tr3:
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	goto st3;
tr10:
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	goto st3;
tr16:
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	goto st3;
tr20:
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	goto st3;
st3:
	if ( ++p == pe )
		goto _test_eof3;
case 3:
	switch( (*p) ) {
		case 0: goto st3;
		case 32: goto st3;
		case 67: goto tr0;
		case 99: goto tr2;
	}
	if ( 9 <= (*p) && (*p) <= 13 )
		goto st3;
	goto st0;
tr2:
	{
    count = 1;
    rest = false;
  }
	goto st4;
tr8:
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st4;
tr15:
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st4;
tr18:
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st4;
tr22:
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    count = 1;
    rest = false;
  }
	goto st4;
st4:
	if ( ++p == pe )
		goto _test_eof4;
case 4:
	switch( (*p) ) {
		case 0: goto tr10;
		case 32: goto tr10;
		case 33: goto tr11;
		case 42: goto st6;
		case 67: goto tr14;
		case 95: goto tr11;
		case 99: goto tr15;
	}
	if ( (*p) > 13 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr13;
	} else if ( (*p) >= 9 )
		goto tr10;
	goto st0;
tr11:
	{
#define NON_NATIVE_ERROR_SIZE 36

    char non_native_msg[NON_NATIVE_ERROR_SIZE];
    snprintf(non_native_msg, NON_NATIVE_ERROR_SIZE,
             "'%c' allowed only after types sSiIlL", *p);
    Exception::argument_error(state, non_native_msg);
  }
	goto st5;
st5:
	if ( ++p == pe )
		goto _test_eof5;
case 5:
	switch( (*p) ) {
		case 0: goto tr10;
		case 32: goto tr10;
		case 67: goto tr14;
		case 99: goto tr15;
	}
	if ( 9 <= (*p) && (*p) <= 13 )
		goto tr10;
	goto st0;
st6:
	if ( ++p == pe )
		goto _test_eof6;
case 6:
	switch( (*p) ) {
		case 0: goto tr16;
		case 32: goto tr16;
		case 67: goto tr17;
		case 99: goto tr18;
	}
	if ( 9 <= (*p) && (*p) <= 13 )
		goto tr16;
	goto st0;
tr13:
	{
    count = (*p) - '0';
  }
	goto st7;
tr19:
	{
    count = count * 10 + ((*p) - '0');
  }
	goto st7;
st7:
	if ( ++p == pe )
		goto _test_eof7;
case 7:
	switch( (*p) ) {
		case 0: goto tr10;
		case 32: goto tr10;
		case 67: goto tr14;
		case 99: goto tr15;
	}
	if ( (*p) > 13 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr19;
	} else if ( (*p) >= 9 )
		goto tr10;
	goto st0;
tr4:
	{
#define NON_NATIVE_ERROR_SIZE 36

    char non_native_msg[NON_NATIVE_ERROR_SIZE];
    snprintf(non_native_msg, NON_NATIVE_ERROR_SIZE,
             "'%c' allowed only after types sSiIlL", *p);
    Exception::argument_error(state, non_native_msg);
  }
	goto st8;
st8:
	if ( ++p == pe )
		goto _test_eof8;
case 8:
	switch( (*p) ) {
		case 0: goto tr3;
		case 32: goto tr3;
		case 67: goto tr7;
		case 99: goto tr8;
	}
	if ( 9 <= (*p) && (*p) <= 13 )
		goto tr3;
	goto st0;
st9:
	if ( ++p == pe )
		goto _test_eof9;
case 9:
	switch( (*p) ) {
		case 0: goto tr20;
		case 32: goto tr20;
		case 67: goto tr21;
		case 99: goto tr22;
	}
	if ( 9 <= (*p) && (*p) <= 13 )
		goto tr20;
	goto st0;
tr6:
	{
    count = (*p) - '0';
  }
	goto st10;
tr23:
	{
    count = count * 10 + ((*p) - '0');
  }
	goto st10;
st10:
	if ( ++p == pe )
		goto _test_eof10;
case 10:
	switch( (*p) ) {
		case 0: goto tr3;
		case 32: goto tr3;
		case 67: goto tr7;
		case 99: goto tr8;
	}
	if ( (*p) > 13 ) {
		if ( 48 <= (*p) && (*p) <= 57 )
			goto tr23;
	} else if ( (*p) >= 9 )
		goto tr3;
	goto st0;
	}
	_test_eof2: cs = 2; goto _test_eof; 
	_test_eof3: cs = 3; goto _test_eof; 
	_test_eof4: cs = 4; goto _test_eof; 
	_test_eof5: cs = 5; goto _test_eof; 
	_test_eof6: cs = 6; goto _test_eof; 
	_test_eof7: cs = 7; goto _test_eof; 
	_test_eof8: cs = 8; goto _test_eof; 
	_test_eof9: cs = 9; goto _test_eof; 
	_test_eof10: cs = 10; goto _test_eof; 

	_test_eof: {}
	if ( p == eof )
	{
	switch ( cs ) {
	case 3: 
	{
    return array;
  }
	break;
	case 2: 
	case 8: 
	case 10: 
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    return array;
  }
	break;
	case 4: 
	case 5: 
	case 7: 
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    return array;
  }
	break;
	case 9: 
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(UBYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    return array;
  }
	break;
	case 6: 
	{
    count = 0;
    rest = true;
  }
	{
    width = 1;
  }
	{
    stop = rest ? size() + 1 : index + width * count;
    if(stop > size()) {
      stop = index + ((size() - index) / width) * width;
    }
  }
	{
    UNPACK_ELEMENTS(BYTE);
  }
	{
    while(count > 0) {
      array->append(state, Qnil);
      count--;
    }
  }
	{
    return array;
  }
	break;
	}
	}

	_out: {}
	}



    if(unpack_first_final && unpack_error && unpack_en_main) {
      // do nothing
    }

    return force_as<Array>(Primitives::failure());
  }
}
