#!/usr/bin/env rake
# -*- Ruby -*-
require 'rubygems'
require 'rake/gempackagetask'

base_spec = Gem::Specification.new do |s|
  s.name = "ffi"

  s.homepage = "http://rubini.us"
  s.summary = "Foreign Function Interface for Ruby - Rubinius Stub Gem"
  s.description = "This gem is bundled with Rubinius to satisfy dependencies on ffi gem. Rubinius provides FFI natively."

  s.version = "1.0.9"

  s.authors = ["Brian Ford"]
  s.email = "bford@engineyard.com"
  s.platform = Gem::Platform::RUBY
  s.files = ["LICENSE", "README", "Rakefile", "lib/ffi.rb"]
  s.require_paths = "lib"
  s.rubygems_version = "1.5.2"

  s.date = Time.now
end

# Rake task to build the default package
Rake::GemPackageTask.new(base_spec) do |pkg|
  pkg.need_tar = true
end

task :default => [:package]
