require 'melbourne'

require 'compiler/compiler'
require 'compiler/stages'
require 'compiler/locals'
require 'compiler/ast'
require 'compiler/generator'
require 'compiler/stack_calculator'
require 'compiler/context'
require 'compiler/iseq'
require 'compiler/opcodes'
require 'compiler/compiled_file'
require 'compiler/evaluator'
require 'compiler/printers'
