#define CONFIG_HOST "@RUBY_PLATFORM@"
#define CONFIG_VERSION "@VERSION@"
#define CONFIG_RUBY_VERSION "@RUBY_VERSION@"
#define CONFIG_RELDATE "@RELDATE@"
#define CONFIG_RUBY_PATCHLEVEL "@RUBY_PATCHLEVEL@"

#define CONFIG_CODEPATH "@CODEPATH@"
#define CONFIG_RBAPATH "@RBAPATH@"
#define CONFIG_EXTPATH "@EXTPATH@"
#define CONFIG_BUILDREV "@BUILDREV@"
#define CONFIG_ENGINE "@ENGINE@"
#define CONFIG_CC "@CMAKE_C_COMPILER@"
#define CONFIG_WORDSIZE @WORDSIZE@
#define CONFIG_BIG_ENDIAN @BIG_ENDIAN@

#cmakedefine CONFIG_ENABLE_DTRACE 1
