#!/usr/bin/env ruby

PR = %r!(.*?)[/]?shotgun/rubinius!

m = PR.match($0)

if m
  # Good to go.
elsif File.symlink?($0)
  path = File.readlink($0)
  m = PR.match(path)
end

my_name = File.basename($0)

prefix = m[1]
prefix = "" if prefix == "./"

unless prefix[0] == ?/
  prefix = File.expand_path File.join(Dir.getwd, prefix)
end

real = File.join(prefix, 'shotgun/rubinius.bin')

# Setup all the crazy library path stuff so that librubinus is picked
# up properly.

@prefix = prefix

def set_env(name)
  addition = "#{@prefix}/shotgun/lib"
  
  if cur = ENV[name]
    ENV[name] = "#{addition}:#{cur}"
  else
    ENV[name] = addition
  end
end

set_env 'LD_LIBRARY_PATH'
set_env 'LD_LIBRARY_PATH_64'
set_env 'SHLIB'
set_env 'LIBPATH'
set_env 'PATH'
set_env 'DYLD_LIBRARY_PATH'
set_env 'DYLD_FALLBACK_LIBRARY_PATH'

ENV['RBX_IN_BUILDDIR'] = "1"

ENV['RBX_PREFIX'] = "#{prefix}/"

unless ENV['RBX_BOOTSTRAP']
  ENV['RBX_BOOTSTRAP'] = "#{prefix}/runtime/bootstrap"
end

unless ENV['RBX_CORE']
  ENV['RBX_CORE'] = "#{prefix}/runtime/core"
end

unless ENV['RBX_PLATFORM']
  ENV['RBX_PLATFORM'] = "#{prefix}/runtime/platform"
end

unless ENV['RBX_LOADER']
  ENV['RBX_LOADER'] = "#{prefix}/runtime/loader.rbc"
end

unless ENV['RBX_PLATFORM_CONF']
  ENV['RBX_PLATFORM_CONF'] = "#{prefix}/runtime/platform.conf"
end

if ARGV[0] == "--gdb"
  ARGV.shift
    
  ENV['PATH'] = "#{prefix}/shotgun:#{ENV['PATH']}"
  args = ['-x', "#{prefix}/shotgun/gdbcommands"]
  if `uname -s` == "Darwin" and `uname -r`.split(".")[0].to_i < 9
    args << '-x' << "#{prefix}/shotgun/gdbenvironment"
  end
  args << '--args' << "/dev/null"

  exec "gdb", *(args + ARGV)
elsif ARGV[0] == "--valgrind"
  ARGV.shift
  args = ['-v', real]
  exec 'valgrind', *(args + ARGV)
elsif ARGV[0] == "--shark"
  ARGV.shift
  puts "Starting up rubinius, then pausing for shark to start"
  pid = fork { sleep 5; exec real, *ARGV }
  exec "shark -o rbxshark -i -1 -a #{pid}"
elsif ARGV[0] == "--dtrace"
  ARGV.shift
  puts "Starting up rubinius, then pausing for dtrace to start"
  pid = fork { sleep 5; exec real, *ARGV }
  exec "dtrace -s #{ENV['SCRIPT']} -p #{pid}"
else
  exec [real, my_name], *ARGV
end
