#!/bin/sh

PREFIX=`echo $0 | sed -e 's/shotgun\/rubinius//'`

REAL=${PREFIX}shotgun/rubinius.bin

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PREFIX}shotgun/lib
export LD_LIBRARY_PATH_64=$LD_LIBRARY_PATH_64:${PREFIX}shotgun/lib
export SH_LIB=$SH_LIB:${PREFIX}shotgun/lib
export LIBPATH=$LIBPATH:${PREFIX}shotgun/lib
export PATH=$PATH:${PREFIX}shotgun/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:${PREFIX}shotgun/lib

if [ "x${PREFIX}" != "x" ]; then

  RUNTIME=${PREFIX}runtime/

  if [ "x${RBX_PREFIX}" = "x" ]; then
    export RBX_PREFIX=${PREFIX}
  fi

  if [ "x${RBX_BOOTSTRAP}" = "x" ]; then
    export RBX_BOOTSTRAP=${RUNTIME}bootstrap
  fi

  if [ "x${RBX_COMPILER}" = "x" ]; then
    export RBX_COMPILER=${RUNTIME}compiler
  fi

  if [ "x${RBX_CORE}" = "x" ]; then
    export RBX_CORE=${RUNTIME}core
  fi

  if [ "x${RBX_LOADER}" = "x" ]; then
    export RBX_LOADER=${RUNTIME}loader.rbc
  fi

  if [ "x${RBX_PLATFORM}" = "x" ]; then
    export RBX_PLATFORM=${RUNTIME}platform
  fi
fi

if test "x$1" = "x--gdb"; then
  shift
  export PATH=${PREFIX}shotgun:$PATH

  gdb_command="gdb -x ${PREFIX}shotgun/gdbcommands"
  if [ `uname -s` = "Darwin" ] && [ `uname -r | cut -d '.' -f 1` -lt "9" ]; then
    gdb_command="${gdb_command} -x ${PREFIX}shotgun/gdbenvironment"
  fi
  gdb_command="${gdb_command} --args /dev/null \"$@\""

  exec $gdb_command
elif test "x$1" = "x--valgrind"; then
  shift
  exec valgrind -v $REAL "$@"
else
  exec $REAL "$@"
fi
