require 'rake/loaders/makefile'

# Setup project files
project_files = common_headers + headers + sources + objects

add_rbx_capi

syck = "syck.#{$DLEXT}"

file syck => project_files

graph_dependencies sources

import dependency_file

desc "Build Syck extension"
task :build => syck
