# Code Generated by ZenTest v. 3.2.0
#                 classname: asrt / meth =  ratio%
#               MemoryBlock:    0 /    7 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require 'gc/memory_block'

class TestMemoryBlock < Test::Unit::TestCase
  def setup
    @block = MemoryBlock.new(256)
  end
  
  def teardown
    @block.deallocate
  end
  
  def test_address
    assert_kind_of Fixnum, @block.address
  end

  def test_byte
    @block.store_byte 0, 47
    out = @block.byte 0
    assert_equal 47, out
  end

  def test_byte_in_bounds_eh
    assert @block.byte_in_bounds?(1)
    assert !@block.byte_in_bounds?(257)
  end

  def test_long
    @block.store_long 0, 47
    out = @block.long 0
    assert_equal 47, out
  end

  def test_long_in_bounds_eh
    assert @block.long_in_bounds?(0)
    assert !@block.long_in_bounds?(65)
  end

  def test_size
    assert_equal 256, @block.size
  end
end
