require 'rake/loaders/makefile'

# Setup project files
project_files = common_headers + headers + sources + objects

add_rbx_capi

add_include_dir ".."
add_shared_lib "crypto"

md5 = "md5.#{$DLEXT}"

file md5 => project_files

graph_dependencies sources, "./../"

import dependency_file

desc "Build Digest/md5 extension"
task :build => md5
