#!/usr/bin/env rake
# -*- Ruby -*-
require 'rubygems'
require 'rake/gempackagetask'

# Base GEM Specification
base_spec = Gem::Specification.new do |spec|
  spec.name = "ruby-debug"

  spec.homepage = "http://rubini.us"
  spec.summary = "Fast Ruby debugger - Rubinius Stub"
  spec.description = <<-EOF
This gem is bundled with Rubinius to satisify any requirements on ruby-debug.
EOF

  spec.version = "0.10.47"

  spec.author = "Evan Phoenix"
  spec.email = "ephoenix@engineyard.com"
  spec.platform = Gem::Platform::RUBY
  spec.require_path = "lib"
  spec.files = ["LICENSE", "README", "Rakefile", "lib/ruby-debug.rb"]

  spec.date = Time.now
end


# Rake task to build the default package
Rake::GemPackageTask.new(base_spec) do |pkg|
  pkg.need_tar = true
end

task :default => [:package]

