#cmakedefine HAVE_ARGZ_APPEND 1
#cmakedefine HAVE_ARGZ_CREATE_SEP 1
#cmakedefine HAVE_ARGZ_H 1
#cmakedefine HAVE_ARGZ_INSERT 1
#cmakedefine HAVE_ARGZ_NEXT 1
#cmakedefine HAVE_ARGZ_STRINGIFY 1
#cmakedefine HAVE_ASSERT_H 1
#cmakedefine HAVE_BCOPY 1
#cmakedefine HAVE_CLOSEDIR 1
#cmakedefine HAVE_CTYPE_H 1
#cmakedefine HAVE_DIRENT_H 1
#cmakedefine HAVE_DLD 1
#cmakedefine HAVE_DLD_H 1
#cmakedefine HAVE_DLERROR 1
#cmakedefine HAVE_DLFCN_H 1
#cmakedefine HAVE_DL_H 1
#cmakedefine HAVE_DYLD 1
#cmakedefine HAVE_ERRNO_H 1
#cmakedefine HAVE_ERROR_T 1
#cmakedefine HAVE_INDEX 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_LIBDL 1
#cmakedefine HAVE_MACH_O_DYLD_H 1
#cmakedefine HAVE_MALLOC_H 1
#cmakedefine HAVE_MEMCPY 1
#cmakedefine HAVE_MEMMOVE 1
#cmakedefine HAVE_MEMORY_H 1
#cmakedefine HAVE_NDIR_H 1
#cmakedefine HAVE_OPENDIR 1
#cmakedefine HAVE_PRELOADED_SYMBOLS 1
#cmakedefine HAVE_READDIR 1
#cmakedefine HAVE_RINDEX 1
#cmakedefine HAVE_SHL_LOAD 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDIO_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRCHR 1
#cmakedefine HAVE_STRCMP 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_STRRCHR 1
#cmakedefine HAVE_SYS_DIR_H 1
#cmakedefine HAVE_SYS_DL_H 1
#cmakedefine HAVE_SYS_NDIR_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine LTDL_DLOPEN_DEPLIBS
#cmakedefine LTDL_OBJDIR "@LTDL_OBJDIR@"
#cmakedefine LTDL_SHLIBPATH_VAR "@LTDL_SHLIBPATH_VAR@"
#cmakedefine LTDL_SHLIB_EXT "@LTDL_SHLIB_EXT@"
#cmakedefine LTDL_SYSSEARCHPATH "@LTDL_SYSSEARCHPATH@"
#cmakedefine NEED_USCORE 1
#cmakedefine error_t @error_t@
