# Setup project files
project_files = common_headers + headers + sources + objects

add_rbx_capi

add_include_dir ".."
add_shared_lib "crypto"

sha1 = "sha1.#{$DLEXT}"

file sha1 => project_files

desc "Build Digest/sha1 extension"
task :build => sha1
