require 'mspec/formatters/base'
require 'mspec/formatters/dotted'
require 'mspec/formatters/specdoc'
require 'mspec/formatters/html'
require 'mspec/formatters/immediate'
require 'mspec/formatters/ci'
