require 'op_code_info'

namespace "doc" do
   namespace "vm" do
     desc "Update YAML doc files with current op codes, source, etc (retains doco)"
     task "yaml" do
       ruby "gen_op_code_yaml.rb"
     end
 

     desc "Generate HTML from YAML"
     task "html"
     
     # Define tasks for each html file on the corresponding YAML file
     OpCode::Info.op_codes.each do |op|
       html = "op_codes/#{op}.html"
       yaml = "op_codes/#{op}.yaml"
       file html => yaml do
         ruby "gen_op_code_html.rb #{op}"
       end
       
       task "html" => html
     end
     
     # Define tasks for each html file on the corresponding textile file
     # Note: requires redcloth gem to convert textile markup to html
     Dir.glob('*.textile').each do |f|
       html = f.chomp('.textile') + '.html'
       file html => f do
         ruby "gen_section_html.rb #{f}"
       end
       
       task "html" => html
     end
     
   end
 end
 
 # Define default task - generate/update HTML
 task "default" => "doc:vm:html"