namespace "doc" do
   namespace "vm" do
     desc "Update YAML doc files with current op codes, source, etc (retains doco)"
     task "yaml" do
       ruby "gen_op_code_yaml.rb"
     end
 

     desc "Generate HTML from YAML"
     task "html"
     
     # Define tasks for each html file on the corresponding YAML file
     Dir.glob('op_codes/*.yaml').each do |f|
       html = f.chomp('.yaml') + '.html'
       op_code = File.basename(f).chomp('.yaml')
       file html => f do
         ruby "gen_op_code_html.rb #{op_code}"
       end
       
       task "html" => html
     end
     
     # Define tasks for each html file on the corresponding textile file
     # Note: requires redcloth gem to convert textile markup to html
     Dir.glob('*.textile').each do |f|
       html = f.chomp('.textile') + '.html'
       file html => f do
         require 'redcloth'
         red = RedCloth.new File.read(f)
         File.open(html, 'w') do |f|
           f.puts red.to_html
         end
       end
       
       task "html" => html
     end
     
   end
 end
 
 # Define default task - generate/update HTML
 task "default" => "doc:vm:html"