/* This file is generated by the build system. Your edits
 * will be lost. See the configure script.
 */

#ifndef NORETURN
#define NORETURN(x) __attribute__ ((noreturn)) x
#endif


#define HAS_EXECINFO         1
#define HAVE_SPT_REUSEARGV   1
#define HAVE_NL_LANGINFO     1
#define HAVE_TM_GMTOFF       1
#define HAVE_TM_ZONE         1
#define HAVE_TIMEZONE        1
#define HAVE_TZNAME          1
#define HAVE_DAYLIGHT        1
#define HAVE_ALLOCA_H        1
#define HAVE_STRING_H        1
#define HAVE_SYS_TIME_H      1
#define HAVE_SYS_TIMES_H     1
#define HAVE_SYS_TYPES_H     1
#define HAVE_UNISTD_H        1
#define HAVE_STDARG_H        1
#define HAVE_VALGRIND_H      1

#define HAVE_DOUBLE           1
#define HAVE_FLOAT            1
#define HAVE_INT              1
#define HAVE_LONG             1
#define HAVE_LONG_LONG        1
#define HAVE_OFF_T            1
#define HAVE_SHORT            1
#define HAVE_SIZE_T           1
#define HAVE_TIME_T           1
#define HAVE_VOIDP            1

#define SIZEOF_DOUBLE         8
#define SIZEOF_FLOAT          4
#define SIZEOF_INT            4
#define SIZEOF_LONG           8
#define SIZEOF_LONG_LONG      8
#define SIZEOF_OFF_T          8
#define SIZEOF_SHORT          2
#define SIZEOF_SIZE_T         8
#define SIZEOF_TIME_T         8
#define SIZEOF_VOIDP          8
