# 
# To change this template, choose Tools | Templates
# and open the template in the editor.
 

require 'rubygems'
require 'bundler'

begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end

require 'rake'

LANG = case ENV['LANG']
       when /utf-8/i then $&
       when /^(.+)\..*$/ then $1 + '.UTF-8'
       else 'en_US.UTF-8'
       end

SET_CMD = case RUBY_PLATFORM 
	  when /mingw32/ then "set"
	  else "export"
	  end

RBX = case RUBY_ENGINE
      when /rbx/ then "rbx -S"
      else ""
      end

task :default => 'generate'

desc 'just generate the site'
task :generate do
  sh "#{SET_CMD} LANG=#{LANG} && #{RBX} jekyll"
end

desc 'serve locally on jekyll'
task :serve do
  sh "#{SET_CMD} LANG=#{LANG} && #{RBX} jekyll --server --auto"
end

desc 'Clean the generated _site dir'
task :clean do
  sh "cd _site && rm -rf *"
end
